services:
  - type: web
    name: flask-chat-app
    env: python
    plan: starter  # or free, but starter is better
    buildCommand: buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chat_db
          property: connectionString

databases:
  - name: chat_db
    plan: free
