services:
  - type: web
    name: flask-chat-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chat_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0  # Change from 3.13 to 3.12

databases:
  - name: chat_db
    plan: free
